apiVersion: v1
kind: Secret
metadata:
  name: db-root-secret
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
type: Opaque
immutable: true
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: default
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
          protocol: TCP
      resources:
        limits:
          cpu: 250m
          memory: 500Mi
        requests:
          cpu: 250m
          memory: 500Mi
      envFrom:
      - secretRef:
          name: db-root-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sql01
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: mysql

