FROM nginx:stable-alpine
COPY ./index.html /usr/share/nginx/html
#RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# docker build . -f qa.dockerfile -t cachac/kubelabs_webapp:1.0.0
# docker push cachac/kubelabs_webapp:1.0.0
