apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  # es posible definir etiquetas para encontrar el PV
  # selector:
  #   matchLabels:
  #     name: static-pv

